### ISSUE TITLE
Parser for `jinahub+docker://name` doesn't work after introducing namespace

### ISSUE THREAD

**Issue by mapleeit** [jina-ai/jina-hubble-sdk#106]
We need to make the parser compatiple for both `jinahub+docker://name/tag` and `jinahub+docker://username/name/tag`

**Comment by delgermurun** [comment]
As we discussed before, current **`jinahub://executor1/tag1`** format conflicts with
next name-spaced **`jinahub://username1/executor1`** format

There is no way to check which format is being used on the client side.
How should we solve this @nomagick?
We must check all possibilities on the backend side, I'm afraid.

**Comment by mapleeit** [comment]
Will `jinahub://username1@executor1` or `jinahub://executor1@username` be an option?

**Comment by nomagick** [comment]
Can we change the scheme? like `jinacloud://username/executor?tag=latest`

**Comment by delgermurun** [comment]
I don't like characters other than `/` 😄 

> Can we change the scheme? like `jinacloud://username/executor?tag=latest`

I like the idea of introducing a new schema (old one only works for old executors).

If we do it how about just following `docker pull jinaai/jina:master-py39-perf` format?
Something like `jinacloud://username1/executor1/:tag1`.

**Comment by nomagick** [comment]
> check all possibilities on the backend side

I don't think it's a good idea. There will be unsolvable cases like user HanXiao vs executor HanXiao.

> I don't like characters other than /

Same to me.

> jinacloud://username1/executor1/:tag1

I think this is ok.

**Comment by mapleeit** [comment]
I remember when I first implemented this, I imaged `jinahub://username1@executor1` as the way to introducing namespace.

**Comment by nomagick** [comment]
We need either `jinahub://username1@executor1` or `jinacloud://whatever`.
@delgermurun Could you make the decision? I'm ok with both. Or ask the team or Han for opinions.

**Comment by delgermurun** [comment]
> Will jinahub://username1@executor1 or ~~jinahub://executor1@username~~ be an option?

@mapleeit What are the reasons for not using the second option? Are there any technical reasons?
If I had to choose one, I would choose the second option because the executor belongs to the user rather than vice versa.

**Comment by delgermurun** [comment]
We have decided to proceed with **`jinaai://executor1@username1/tag1`**

https://jinaai.slack.com/archives/C023A7RAPGR/p1668091204003139?thread_ts=1668072562.156489&cid=C023A7RAPGR

**Comment by delgermurun** [comment]
A new namespaced URI is `jinaai...://username1/executor1:tag1`.
