### ISSUE TITLE
Installing Jina Hubble SDK in virtual environments screws up global Docker image building

### ISSUE THREAD

**Issue by fa9r** [jina-ai/jina-hubble-sdk#161]
I installed `jina-hubble-sdk` in a pyenv virtualenv when using discoart. Apparently, that changed something somewhere in my Docker config/settings/??? which led to the following error when building images in other environments:

```
...
... python3.10/site-packages/docker/auth.py:284 in _get_store_instance
... python3.10/site-packages/docker/credentials/store.py:2 in __init__
InitializationError: docker-credential-jina-hubble not installed or not available in PATH
```

I found two workarounds to fix this:
- Running `pip install jina-hubble-sdk` in all other environments (obviously not ideal since it kinda defeats the point of having virtual environments in the first place).
- Running `jina auth login` and then explicitly calling `jina auth logout` in my discoart venv.

It seems to me that this is an issue that happens when the user doesn't explicitly call `jina auth logout` before switching environments. I assume this a common usage pattern and it was a quite annoying thing to debug, so I'd suggest to look into this and make the Docker changes less intrusive so Docker itself still works without `jina-hubble-sdk` installed.

**Comment by nomagick** [comment]
Hi @fa9r. 
Thank you for reaching out.

This is indeed a known issue.

The issue is related to the specific implementation of `docker-py`.
I submitted a [PR](https://github.com/docker/docker-py/pull/3080) to them, which was merged a while ago. 

This should be fixed after they make the next release.

**Comment by fa9r** [comment]
Somehow missed this. Thanks a lot for fixing it @nomagick ❤️
