### ISSUE TITLE
[yellow bold]c006e4bf-e9e8-11ed-bb99-80913334fb46[/]

### ISSUE THREAD

**Issue by bigKeter** [jina-ai/jina-hubble-sdk#171]
Hello,

I am getting the following problem: 
Exception: DownstreamServiceFailureError: Executor normalization failed(5000): 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte session_id: c006e4bf-e9e8-11ed-bb99-80913334fb46

The session ID is the following:
[yellow bold]c006e4bf-e9e8-11ed-bb99-80913334fb46[/]

Thank you for the help.

**Comment by hari4742** [comment]
I am facing same issue, can you tell me how you resolved this?
