### ISSUE TITLE
Create trace_id from client side and send to server, show the id on error

### ISSUE THREAD

**Issue by nomagick** [jina-ai/jina-hubble-sdk#55]
We would like the client side to generate something like the `__trace_id` and carry it to the server.

So when the client receives an error, the user always gets an id for us to debug.

The trace id parameter can be passed in HTTP query so it may aslo be recorded at gateway level.

**Comment by floralatin** [comment]
mmm.  Now in` jina-hubble-sdk`, it has `seession_id` to trace every request, and we also  debug it according to grafana log.

**Comment by floralatin** [comment]
@nomagick  maybe we should close this ticket. do you think?

**Comment by mapleeit** [comment]
- [ ] Errors raised by client itself doesn't print the `session-id`
- [ ] Need to check that if the `session-id` is sent inside the header

**Comment by floralatin** [comment]
>  Need to check that if the session-id is sent inside the header

Session-id is sent inside the header.

**Comment by floralatin** [comment]
#99
