### ISSUE TITLE
allow checking if user already logged in

### ISSUE THREAD

**Issue by jupyterjazz** [jina-ai/jina-hubble-sdk#65]
every time `hubble.login` is [called in the finetuner](https://github.com/jina-ai/finetuner/blob/8829ec7368d33705493ae83e0cc5496ab8e062c5/finetuner/__init__.py#L33) new session is created, overwriting `jina_token` in config.json

we should allow checking if the user has already logged in, we could have an argument like `force` which [exists in the api part](https://github.com/jina-ai/jina-hubble-sdk/blob/b16a0e699920305633864ae44b2fad0e43522f84/hubble/api.py#L20), but not inside [the core](https://github.com/jina-ai/jina-hubble-sdk/blob/4dc5db98b6a303faa4e65aa6bad77db8dc223dd0/hubble/utils/auth.py#L30).

**Comment by delgermurun** [comment]
@jupyterjazz We released this feature. Please check it out.
