### ISSUE TITLE
use `xattr` for executor id caching

### ISSUE THREAD

**Issue by nomagick** [jina-ai/jina-hubble-sdk#90]
For the caching of the executor id:

We used to use secret files for executor id caching. Known as the `.jina` directory.
This is problematic because user my upload the secret file to git which causes security issues.

Then we switched to an `inode` based approach. Known as `~/.cache/jina`.
This is better as it got rid of security issues and can live through directory moves.
But it's still not enough because it cannot live through directory copy and file system change.

It came to me recently that we can use the `xattr` approach.
This will have a simular experience to the secret file approach but no security issues because git doesn't track file xattrs.
Still missing though: it won't live through git clones. But this is somewhat intended.

xattr:  https://man7.org/linux/man-pages/man2/lsetxattr.2.html

**Comment by nomagick** [comment]
People usually getting `IdentifierNamespaceOccupiedError` when intend to update executors because the Id cache was somehow missing.

**Comment by floralatin** [comment]
This issues: https://jinaai.slack.com/archives/C023A7RAPGR/p1666591137378519, is not the Id cache caused. it just because the  `manifest.yml` info has conflict with `congfig.yml`.

**Comment by floralatin** [comment]
And about `IdentifierNamespaceOccupiedError`, I think we should use `username/id`  to replace  `id`

**Comment by nomagick** [comment]
Consider removing the id cache in https://github.com/jina-ai/jina-hubble-sdk/issues/125

**Comment by mapleeit** [comment]
Closed since we decided to remove cache entirely.
